name: CMake

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run:   |
             sudo apt update
             sudo apt install g++-10 cmake ninja-build clang-10 libclang-10-dev
      shell: bash
      
    - run: ls /usr/lib && ls /usr/lib/llvm-9/include/clang

    - name: create build dir
      run: mkdir ${{github.workspace}}/build
    
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -S ${{github.workspace}} -B $GITHUB_WORKSPACE -G Ninja
      env:
        CXX:  g++-10

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE --config $BUILD_TYPE --target all -j 10
